Fix docs
yiisoft/injector pull request #95
Opened 2024-05-18 15:12 UTC by luizcmarin

- Contents of 'docs/guide/en/readme.md' appended to main 'readme.md' so that 'every readme.md has general usage' etc

- Decide whether to keep - Guide: [Russian](docs/guide/ru/README.md)

2024-05-18 16:43 UTC, vjik requested changes

2024-05-18 16:43 UTC, vjik commented on docs/guide/en/README.md
Why do you remove it?

2024-05-18 16:43 UTC, vjik commented on README.md
> -#### Features
Current order of blocks is OK.

2024-05-18 16:43 UTC, vjik commented on image/algorithm.graphml
Why do you move this files?

2024-05-19 08:54 UTC, luizcmarin commented on docs/guide/en/README.md
You told me that every file should have a "## General usage". There was no "## General usage" in the main readme.md.
So I did what I mentioned:
> * Contents of 'docs/guide/en/readme.md' appended to main 'readme.md' so that 'every readme.md has general usage' etc

and removed the file because I found it unnecessary to keep it.

2024-05-19 09:04 UTC, luizcmarin commented on image/algorithm.graphml
Because they are used by the main readme.md, although coincidentally they are used within 'docs'; I thought that "if it's not part of the documentation, it should be in the root". If they ever decide to modify the 'docs' folder, it will not affect other files outside of that folder.

2024-05-19 13:45 UTC, vjik commented on docs/guide/en/README.md
Currently docs in master branch is OK. Readme already container general usage (basic example).

2024-05-19 13:46 UTC, vjik commented on image/algorithm.graphml
It's language-specfic files. Readme used english images. It's OK.

2024-05-20 08:51 UTC, luizcmarin commented on docs/guide/en/README.md
There are differences between "## Basic Example" and "## General usage". I chose the information that seemed most current to me.
It also seemed to me that there was repetition of information, as in "## Reflection caching" and "## Caching reflection objects".
All other information contained in https://github.com/yiisoft/injector/blob/master/docs/guide/en/README.md is present in the main readme.md.
Well, you are the experts and I want to learn from you. Please guide me on how to proceed when situations like this arise.

2024-05-20 10:45 UTC, vjik commented on docs/guide/en/README.md
In readme should be section "General Usage". Also in guides should be file `README.md`.

2024-05-20 16:15 UTC, luizcmarin commented on docs/guide/en/README.md
> In readme should be section "General Usage". Also in guides should be file `README.md`.

You're just explaining it to me right? Because there are no more tabs, except for the Russian language, in this PR of mine.
OR should I undo everything I did and leave it as it was?
*Google translates, but it doesn't always correctly convey what we mean.

2024-05-28 05:26 UTC, vjik commented on docs/guide/en/README.md
Currently docs in master branch is OK. Keep as is.

2024-05-28 11:59 UTC, roxblnfk commented on docs/guide/en/README.md
I wouldn't remove the docs from the `docs` folder, at least because we will generate the documentation on the website based on it.

2024-05-28 12:14 UTC, roxblnfk requested changes
I don't see the need to duplicate the documentation in the readme. A small usage example in the readme is OK, but explanations and advanced usages should only be in the documentation.

And as I've already mentioned before, the main point of keeping all the documentation in one place is that we plan to generate it from there onto the website, rather than assembling it piecemeal from the readme.

Therefore, there's no need to move out of the `docs` the algorithm files and transfer all the English documentation to the readme.

2024-05-29 09:07 UTC, luizcmarin commented
@rox, thanks for the explanation. You know I'm new here. I still don't really understand how you work as a team and how you planned the development of Yii3. Your explanation helped me to understand the documentation part better. I'll try to go back a little on my modifications and please help me to be useful in your work.

2024-05-29 09:54 UTC, closed without merging