Adjust pretty name of closures on PHP 8.4
yiisoft/injector pull request #96
Opened 2024-05-25 06:38 UTC by staabm

related to https://github.com/php/php-src/pull/13550

see analog symfony change: https://github.com/symfony/symfony/pull/54614

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

2024-05-25 11:03 UTC, roxblnfk commented
Need to add a test with PHP 8.4

2024-05-25 12:19 UTC, staabm commented
requires https://github.com/Roave/infection-static-analysis-plugin/pull/497

2024-07-07 07:48 UTC, samdark approved these changes

2024-07-08 07:52 UTC, vjik requested changes
Need test with PHP 8.4

2025-03-13 18:38 UTC, vjik commented
Closed in favor #105

2025-03-13 18:38 UTC, closed without merging