Fix callable call
yiisoft/injector pull request #98
Opened 2024-07-01 18:13 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

Reflections and other internal functions don't provide necessary information such as `line` or `file` if they're used during trace. So changing callable call to a regular `$callable(...$args)` solves this. There're proves:

### Current version
<img width="1326" alt="image" src="https://github.com/yiisoft/injector/assets/6815714/eff42788-92c1-41ba-b437-6774f1e467e0">
<img width="759" alt="image" src="https://github.com/yiisoft/injector/assets/6815714/2d4e431b-523b-4eac-b379-a069622cbfe4">

### Fixed version
<img width="1332" alt="image" src="https://github.com/yiisoft/injector/assets/6815714/f49c3977-a820-41e3-a6e3-4329b39137e3">
<img width="723" alt="image" src="https://github.com/yiisoft/injector/assets/6815714/6cfbae76-579c-4281-ad57-7d174f85a564">

2024-07-01 18:22 UTC, roxblnfk commented
Could you add a test case?

2024-07-02 14:55 UTC, samdark approved these changes
Nice! A changelog is needed. A test case would be awesome to have as well.

2024-07-03 04:58 UTC, vjik requested changes
Need info in changelog

2024-07-03 05:00 UTC, vjik commented
@roxblnfk @samdark What does tests you ask about? Already exists many tests of `Injector::invoke()`: https://github.com/yiisoft/injector/blob/master/tests/Common/InjectorTest.php

2024-07-03 06:45 UTC, samdark approved these changes

2024-07-03 07:06 UTC, samdark commented
@vjik these are about trace improvements.

2024-07-03 08:32 UTC, roxblnfk approved these changes

2024-07-03 09:56 UTC, vjik approved these changes

2024-07-03 09:56 UTC, vjik commented on CHANGELOG.md
> +- Enh #98: Fix callable call (@xepozz)
```suggestion
- Enh #98: Refactor `Injector::invoke()` for improve debug trace (@xepozz)
```

2024-07-06 18:02 UTC, merged